// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "delgme1",
            "email": "delgme1vzw@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/ip-map/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Maintenance"
                ],
                "summary": "Allows the user to create a new entry in CIDR IP - Country table",
                "parameters": [
                    {
                        "description": "IP (CIDR IPv4 or IPv6) and Country",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CIDRIPCountryPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/datastore.MappedIpCountryRecord"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Maintenance"
                ],
                "summary": "Allows the user to delete an entry in CIDR IP - Country table by the CIDR IP",
                "parameters": [
                    {
                        "description": "IP (CIDR IPv4 or IPv6)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CIDRIPPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Maintenance"
                ],
                "summary": "Allows the user to update an entry in CIDR IP - Country table by CIDR IP",
                "parameters": [
                    {
                        "description": "IP (CIDR IPv4 or IPv6) and Country",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CIDRIPCountryPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/datastore.MappedIpCountryRecord"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/v1/ip-map/{ip}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Maintenance"
                ],
                "summary": "Allows the user to check what country a CIDR IP is mapped to",
                "parameters": [
                    {
                        "type": "string",
                        "default": "2001:200::/32",
                        "example": "2001:200::/32",
                        "description": "CIDR IP (IPv4 or IPv6)",
                        "name": "ip",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/datastore.MappedCountry"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/v1/whitelist-status/{ip}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Whitelist"
                ],
                "summary": "Allows the user to check if a CIDR IP is whitelisted for the given countries",
                "parameters": [
                    {
                        "type": "string",
                        "default": "2001:200::",
                        "example": "2001:200::",
                        "description": "Single IP (IPv4 or IPv6)",
                        "name": "ip",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "France,Uganda",
                        "example": "France,Uganda",
                        "description": "Comma-separated countries",
                        "name": "countries",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/datastore.WhitelistedResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "datastore.MappedCountry": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                }
            }
        },
        "datastore.MappedIpCountryRecord": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                }
            }
        },
        "datastore.WhitelistedResults": {
            "type": "object",
            "properties": {
                "whitelisted": {
                    "type": "boolean"
                }
            }
        },
        "main.CIDRIPCountryPayload": {
            "type": "object",
            "required": [
                "country",
                "ip"
            ],
            "properties": {
                "country": {
                    "type": "string",
                    "example": "Japan"
                },
                "ip": {
                    "type": "string",
                    "example": "2001:200::/32"
                }
            }
        },
        "main.CIDRIPPayload": {
            "type": "object",
            "required": [
                "ip"
            ],
            "properties": {
                "ip": {
                    "type": "string",
                    "example": "2001:200::/32"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Country Whitelister API",
	Description:      "API to retrieve country whitelist status based on IP",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
